map_name: de_dust2
regions:
  - name: A Site
    polygon:
      - [760, 120]
      - [980, 120]
      - [980, 320]
      - [760, 320]
  - name: Mid
    polygon:
      - [460, 220]
      - [740, 220]
      - [740, 460]
      - [460, 460]
  - name: B Site
    polygon:
      - [120, 420]
      - [360, 420]
      - [360, 660]
      - [120, 660]
